'use strict';

/* jasmine specs for services go here */

describe('ooUtils', function() {

    describe('parseXml', function() {
        it('should return xml with plain diagram', function() {
            var xml = '<mxfile userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36" type="browser"><diagram>&lt;mxGraphModel dx="800" dy="800" grid="1" guides="1" tooltips="1" connect="1" fold="1" page="1" pageScale="1" pageWidth="826" pageHeight="1169" style="default-style2"&gt;&lt;root&gt;&lt;mxCell id="0"/&gt;&lt;mxCell id="1" parent="0"/&gt;&lt;mxCell id="2" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="3" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="4" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="5" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="6" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="7" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="8" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="9" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;/root&gt;&lt;/mxGraphModel&gt;</diagram></mxfile>';
            var actual = ooUtils.parseXml(xml);
            var expected = 'mxfile';
            expect(actual.documentElement.nodeName).toEqual(expected);
        });
        it('should return xml with compressed diagram', function() {
            var xml = '<mxfile userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36" type="browser"><diagram>JTNDbXhHcmFwaE1vZGVsJTIwZHglM0QlMjI4MDAlMjIlMjBkeSUzRCUyMjgwMCUyMiUyMGdyaWQlM0QlMjIxJTIyJTIwZ3VpZGVzJTNEJTIyMSUyMiUyMHRvb2x0aXBzJTNEJTIyMSUyMiUyMGNvbm5lY3QlM0QlMjIxJTIyJTIwZm9sZCUzRCUyMjElMjIlMjBwYWdlJTNEJTIyMSUyMiUyMHBhZ2VTY2FsZSUzRCUyMjElMjIlMjBwYWdlV2lkdGglM0QlMjI4MjYlMjIlMjBwYWdlSGVpZ2h0JTNEJTIyMTE2OSUyMiUyMHN0eWxlJTNEJTIyZGVmYXVsdC1zdHlsZTIlMjIlM0UlM0Nyb290JTNFJTNDbXhDZWxsJTIwaWQlM0QlMjIwJTIyJTJGJTNFJTNDbXhDZWxsJTIwaWQlM0QlMjIxJTIyJTIwcGFyZW50JTNEJTIyMCUyMiUyRiUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyMiUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyMyUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNCUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNSUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNiUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNyUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQyUyRnJvb3QlM0UlM0MlMkZteEdyYXBoTW9kZWwlM0U=</diagram></mxfile>';
            var actual = ooUtils.parseXml(xml);
            var expected = 'mxfile';
            expect(actual.documentElement.nodeName).toEqual(expected);
        });
    });
    describe('extractDiagram', function() {
        it('should exception when string diagram from non base 64', function() {
            var xml = '<mxfile userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36" type="browser"><diagram>&lt;mxGraphModel dx="800" dy="800" grid="1" guides="1" tooltips="1" connect="1" fold="1" page="1" pageScale="1" pageWidth="826" pageHeight="1169" style="default-style2"&gt;&lt;root&gt;&lt;mxCell id="0"/&gt;&lt;mxCell id="1" parent="0"/&gt;&lt;mxCell id="2" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="3" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="4" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="5" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="6" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="300" height="300" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="7" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="8" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;mxCell id="9" value="Process" vertex="1" parent="1"&gt;&lt;mxGeometry x="10" y="10" width="200" height="200" as="geometry"/&gt;&lt;/mxCell&gt;&lt;/root&gt;&lt;/mxGraphModel&gt;</diagram></mxfile>';
            var actual = true;
            try{
                ooUtils.extractDiagram(xml);
                // exception must jump lines below
                actual=false;
                expect(false).toBeTruthy();
            } catch(e){
                expect(actual).toBeTruthy();
            }

        });
        it('should work with compressed diagram', function() {
            var xml = '<mxfile userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36" type="browser"><diagram>JTNDbXhHcmFwaE1vZGVsJTIwZHglM0QlMjI4MDAlMjIlMjBkeSUzRCUyMjgwMCUyMiUyMGdyaWQlM0QlMjIxJTIyJTIwZ3VpZGVzJTNEJTIyMSUyMiUyMHRvb2x0aXBzJTNEJTIyMSUyMiUyMGNvbm5lY3QlM0QlMjIxJTIyJTIwZm9sZCUzRCUyMjElMjIlMjBwYWdlJTNEJTIyMSUyMiUyMHBhZ2VTY2FsZSUzRCUyMjElMjIlMjBwYWdlV2lkdGglM0QlMjI4MjYlMjIlMjBwYWdlSGVpZ2h0JTNEJTIyMTE2OSUyMiUyMHN0eWxlJTNEJTIyZGVmYXVsdC1zdHlsZTIlMjIlM0UlM0Nyb290JTNFJTNDbXhDZWxsJTIwaWQlM0QlMjIwJTIyJTJGJTNFJTNDbXhDZWxsJTIwaWQlM0QlMjIxJTIyJTIwcGFyZW50JTNEJTIyMCUyMiUyRiUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyMiUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyMyUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNCUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMjAwJTIyJTIwaGVpZ2h0JTNEJTIyMjAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNSUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNiUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQ214Q2VsbCUyMGlkJTNEJTIyNyUyMiUyMHZhbHVlJTNEJTIyUHJvY2VzcyUyMiUyMHZlcnRleCUzRCUyMjElMjIlMjBwYXJlbnQlM0QlMjIxJTIyJTNFJTNDbXhHZW9tZXRyeSUyMHglM0QlMjIxMCUyMiUyMHklM0QlMjIxMCUyMiUyMHdpZHRoJTNEJTIyMzAwJTIyJTIwaGVpZ2h0JTNEJTIyMzAwJTIyJTIwYXMlM0QlMjJnZW9tZXRyeSUyMiUyRiUzRSUzQyUyRm14Q2VsbCUzRSUzQyUyRnJvb3QlM0UlM0MlMkZteEdyYXBoTW9kZWwlM0U=</diagram></mxfile>';
            var actual = ooUtils.extractDiagram(xml);
            var expected = '<mxGraphModel dx="800" dy="800" grid="1" guides="1" tooltips="1" connect="1" fold="1" page="1" pageScale="1" pageWidth="826" pageHeight="1169" style="default-style2"><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="2" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="200" height="200" as="geometry"/></mxCell><mxCell id="3" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="200" height="200" as="geometry"/></mxCell><mxCell id="4" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="200" height="200" as="geometry"/></mxCell><mxCell id="5" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="300" height="300" as="geometry"/></mxCell><mxCell id="6" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="300" height="300" as="geometry"/></mxCell><mxCell id="7" value="Process" vertex="1" parent="1"><mxGeometry x="10" y="10" width="300" height="300" as="geometry"/></mxCell></root></mxGraphModel>';
            expect(expected).toEqual(actual);
        });
    });
});